version: '3'

services:
  db:
    image: postgres:14.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_PASSWORD: password
      DATABASE_URL: postgresql://postgres:password@db:5432/mydb?schema=public
      DB_USER: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      SECRET_KEY: testApplication
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres-data: